[project]
name = "wasabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.2",
    "dotfiles>=0.6.5",
    "fastapi[standard]>=0.136.3",
    "groq>=1.4.0",
    "loguru>=0.7.3",
    "mypy>=2.1.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "ruff>=0.15.16",
    "uvicorn[standard]>=0.49.0",
]

[build-system]
requires = ["uv_build<0.12"]
build-backend = "uv_build"

[tool.uv]
package = true

[project.scripts]
wasabot-dev = "wasabot.cli:dev"
wasabot-prod = "wasabot.cli:prod"
